### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by leonardohofling** [leonardohof/cinex#2]
testing

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [http://localhost:8082/#/task/1](http://localhost:8082/#/task/1)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [http://localhost:8082/#/task/1](http://localhost:8082/#/task/1)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [http://localhost:8082/#/task/3](http://localhost:8082/#/task/3)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by gitpaybot** [comment]
Gitpay is an Open Source platform to reward contributors to get things done 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [http://localhost:8082/#/task/7](http://localhost:8082/#/task/7)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by gitpaybot** [comment]
hello {{github_user}},

Here's is Gitpaybot with good news! You have a bounty to claim :-)

There's a bounty of $ {{amount}} for a task you solved on Gitpay.

If you have a Pull Request merged, please claim on Gitpay (https://gitpay.me) on the issue:
{{gitPayURL}}

Please set the title of your pull request to *issue#{{issue_id}}* and go in _Solve issue_ and send your Pull Request URL.

**Comment by gitpaybot** [comment]
hello {{github_user}},

Here's is Gitpaybot with good news! You have a bounty to claim :-)

There's a bounty of $ {{amount}} for a task you solved on Gitpay.

If you have a Pull Request merged, please claim on Gitpay (https://gitpay.me) on the issue:
{{gitPayURL}}

Please set the title of your pull request to *issue#{{issue_id}}* and go in _Solve issue_ and send your Pull Request URL.

**Comment by gitpaybot** [comment]
hello undefined,

Here's is Gitpaybot with good news! You have a bounty to claim :-)

There's a bounty of $ 50 for a task you solved on Gitpay.

If you have a Pull Request merged, please claim on Gitpay (https://gitpay.me) on the issue:
{{gitPayURL}}

Please set the title of your pull request to *issue#7* and go in _Solve issue_ and send your Pull Request URL.

**Comment by gitpaybot** [comment]
hello undefined,

Here's is Gitpaybot with good news! You have a bounty to claim :-)

There's a bounty of $ 50 for a task you solved on Gitpay.

If you have a Pull Request merged, please claim on Gitpay (https://gitpay.me) on the issue:
{{gitPayURL}}

Please set the title of your pull request to *issue#7* and go in _Solve issue_ and send your Pull Request URL.

**Comment by gitpaybot** [comment]
hello ,

Here's is Gitpaybot with good news! You have a bounty to claim :-)

There's a bounty of $ 50 for a task you solved on Gitpay.

If you have a Pull Request merged, please claim on Gitpay (https://gitpay.me) on the issue:
http://localhost:8082/#/task/7

Please set the title of your pull request to *issue#7* and go in _Solve issue_ and send your Pull Request URL.
